name: flutter_mgr5
description: Flutter mgr5 ui library

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  xml: ^5.3.1
  flutter_html: ^2.2.1
  url_launcher: ^6.0.20
  mask_text_input_formatter: ^2.1.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

