name: flutter_mgr5
description: Flutter mgr5 ui library

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  xml: ^6.3.0
  flutter_html: ^3.0.0-beta.1
  url_launcher: ^6.0.20
  mask_text_input_formatter: ^2.1.0
  shimmer: ^3.0.0
  material_table_view: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

